# Generated by Django 4.1.9 on 2023-06-09 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Salario')),
                ('salario_mes', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Salario Mês')),
                ('vt', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='VT')),
                ('vr', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='VR')),
                ('cesta', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='CESTA')),
                ('sindicato', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('cbo', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteGI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('cod_cliente', models.IntegerField()),
                ('responsavel_filial', models.CharField(max_length=250)),
                ('telefone_filial', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='contract_templates/')),
            ],
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
                ('admission_date', models.DateField()),
                ('rg', models.CharField(max_length=20)),
                ('orgao_emissor_rg', models.CharField(max_length=30)),
                ('uf_rg', models.CharField(max_length=2)),
                ('data_emissao_rg', models.DateField()),
                ('n_ctps', models.CharField(max_length=30)),
                ('serie', models.CharField(max_length=30)),
                ('uf_ctps', models.CharField(max_length=2)),
                ('data_emissao_ctps', models.DateField()),
                ('endereco', models.CharField(max_length=250)),
                ('cep', models.CharField(max_length=30)),
                ('celular', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=250)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissao.base')),
            ],
        ),
        migrations.AddField(
            model_name='base',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissao.cargo'),
        ),
        migrations.AddField(
            model_name='base',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissao.clientegi'),
        ),
    ]
