# Generated by Django 4.1.9 on 2023-06-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
