# Generated by Django 4.1.9 on 2023-06-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='cbo',
            field=models.CharField(default='123', max_length=250),
            preserve_default=False,
        ),
    ]
