# Generated by Django 4.1.9 on 2023-06-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissao', '0002_alter_collaborator_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Salario Hora'),
        ),
        migrations.AlterField(
            model_name='base',
            name='salario_mes',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Salario Mensal'),
        ),
    ]
