# Generated by Django 4.1.9 on 2023-06-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissao', '0005_alter_collaborator_uf_ctps_alter_collaborator_uf_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='cep',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='n_ctps',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='serie',
            field=models.CharField(max_length=5),
        ),
    ]
