# Generated by Django 4.1.9 on 2023-06-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissao', '0007_alter_collaborator_celular_alter_collaborator_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
