# Generated by Django 4.1.9 on 2023-06-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissao', '0008_alter_collaborator_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='celular',
            field=models.CharField(max_length=13),
        ),
    ]
