# Generated by Django 4.1.9 on 2023-06-16 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissao', '0010_basecnpj_baseinfocontratos_competencias_notas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='baseinfocontratos',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='baseinfocontratos2',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='baseinfocontratos3',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='baseinfocontratos4',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='baseinfocontratos5',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='baseinfocontratos6',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='baseinfocontratos7',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='baseinfocontratos8',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='cnpj_da_nota',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='competencia_nota',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='competencia_nota_ans',
        ),
        migrations.DeleteModel(
            name='BaseCNPJ',
        ),
        migrations.DeleteModel(
            name='BaseInfoContratos',
        ),
        migrations.DeleteModel(
            name='Competencias',
        ),
        migrations.DeleteModel(
            name='Notas',
        ),
    ]
