# Generated by Django 4.1.9 on 2023-06-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecnpj',
            name='tx_adm',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='taxa Adm'),
        ),
    ]
