# Generated by Django 4.1.9 on 2023-06-16 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_alter_basecnpj_tx_adm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencias',
            options={},
        ),
        migrations.RemoveField(
            model_name='competencias',
            name='testelogico',
        ),
    ]
